In [1]:
#notebooks/01_data_ingestion_exploration.ipynb
# Data Loading and Basic Overview

In [2]:
import pandas as pd

In [3]:
data_path = "../data/raw/consumer_complaints.csv"
df = pd.read_csv(data_path, low_memory = False)

In [4]:
# View first few rows
print("Sample rows:")
display(df.head())

Sample rows:

,date_received,product,sub_product,issue,sub_issue,consumer_complaint_narrative,company_public_response,company,state,zipcode,tags,consumer_consent_provided,submitted_via,date_sent_to_company,company_response_to_consumer,timely_response,consumer_disputed?,complaint_id
0,08/30/2013,Mortgage,Other mortgage,"Loan modification,collection,foreclosure",NaN,NaN,NaN,U.S. Bancorp,CA,95993,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511074
1,08/30/2013,Mortgage,Other mortgage,"Loan servicing, payments, escrow account",NaN,NaN,NaN,Wells Fargo & Company,CA,91104,NaN,NaN,Referral,09/03/2013,Closed with explanation,Yes,Yes,511080
2,08/30/2013,Credit reporting,NaN,Incorrect information on credit report,Account status,NaN,NaN,Wells Fargo & Company,NY,11764,NaN,NaN,Postal mail,09/18/2013,Closed with explanation,Yes,No,510473
3,08/30/2013,Student loan,Non-federal student loan,Repaying your loan,Repaying your loan,NaN,NaN,"Navient Solutions, Inc.",MD,21402,NaN,NaN,Email,08/30/2013,Closed with explanation,Yes,Yes,510326
4,08/30/2013,Debt collection,Credit card,False statements or representation,Attempted to collect wrong amount,NaN,NaN,Resurgent Capital Services L.P.,GA,30106,NaN,NaN,Web,08/30/2013,Closed with explanation,Yes,Yes,511067

In [5]:
# Overview
print("Dataset Info:")
df_info = df.info()
df_info

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555957 entries, 0 to 555956
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date_received                 555957 non-null  object
 1   product                       555957 non-null  object
 2   sub_product                   397635 non-null  object
 3   issue                         555957 non-null  object
 4   sub_issue                     212622 non-null  object
 5   consumer_complaint_narrative  66806 non-null   object
 6   company_public_response       85124 non-null   object
 7   company                       555957 non-null  object
 8   state                         551070 non-null  object
 9   zipcode                       551452 non-null  object
 10  tags                          77959 non-null   object
 11  consumer_consent_provided     123458 non-null  object
 12  submitted_via                 555957 non-null  object
 13  date_sent_to_company          555957 non-null  object
 14  company_response_to_consumer  555957 non-null  object
 15  timely_response               555957 non-null  object
 16  consumer_disputed?            555957 non-null  object
 17  complaint_id                  555957 non-null  int64
dtypes: int64(1), object(17)
memory usage: 76.3+ MB

In [6]:
# Missing values
print("Missing Values (in %):")
missing = df.isnull().mean().sort_values(ascending=False) * 100
display(missing)

Missing Values (in %):

consumer_complaint_narrative    87.983603
tags                            85.977513
company_public_response         84.688744
consumer_consent_provided       77.793606
sub_issue                       61.755675
sub_product                     28.477382
state                            0.879025
zipcode                          0.810314
date_sent_to_company             0.000000
consumer_disputed?               0.000000
timely_response                  0.000000
company_response_to_consumer     0.000000
date_received                    0.000000
submitted_via                    0.000000
product                          0.000000
company                          0.000000
issue                            0.000000
complaint_id                     0.000000
dtype: float64

In [7]:
# Basic stats for numeric columns
print("Descriptive Stats (Numerics):")
display(df.describe())

Descriptive Stats (Numerics):

       complaint_id
count  5.559570e+05
mean   9.600510e+05
std    5.504296e+05
min    1.000000e+00
25%    4.863230e+05
50%    9.737830e+05
75%    1.441702e+06
max    1.895894e+06

In [8]:
# Unique values per column
print("Unique Value Counts:")
unique_values = df.nunique().sort_values(ascending=False)
# display(df.nunique().sort_values(ascending=False))
display(unique_values)

Unique Value Counts:

complaint_id                    555957
consumer_complaint_narrative     65646
zipcode                          27052
company                           3605
date_received                     1608
date_sent_to_company              1557
issue                               95
sub_issue                           68
state                               62
sub_product                         46
product                             11
company_public_response             10
company_response_to_consumer         8
submitted_via                        6
consumer_consent_provided            4
tags                                 3
timely_response                      2
consumer_disputed?                   2
dtype: int64

In [10]:
# Save summary
summary_path = "../outputs/profiling/data_overview_summary.md"
with open(summary_path, "w") as f:
    f.write("### Data Overview\n")
    f.write(str(df.info(buf=None)))
    f.write("\n\nMissing Values:\n")
    f.write(str(missing)) 
    f.write("\n\nUnique Value Counts")
    f.write(str(unique_values))
print(f"Data Ingestiona Exploration summary written to {summary_path}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 555957 entries, 0 to 555956
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   date_received                 555957 non-null  object
 1   product                       555957 non-null  object
 2   sub_product                   397635 non-null  object
 3   issue                         555957 non-null  object
 4   sub_issue                     212622 non-null  object
 5   consumer_complaint_narrative  66806 non-null   object
 6   company_public_response       85124 non-null   object
 7   company                       555957 non-null  object
 8   state                         551070 non-null  object
 9   zipcode                       551452 non-null  object
 10  tags                          77959 non-null   object
 11  consumer_consent_provided     123458 non-null  object
 12  submitted_via                 555957 non-null  object
 13  date_sent_to_company          555957 non-null  object
 14  company_response_to_consumer  555957 non-null  object
 15  timely_response               555957 non-null  object
 16  consumer_disputed?            555957 non-null  object
 17  complaint_id                  555957 non-null  int64
dtypes: int64(1), object(17)
memory usage: 76.3+ MB
Data Ingestiona Exploration summary written to ../outputs/profiling/data_overview_summary.md